### ISSUE TITLE
ska2anm does not work when building librw with gl3 backend

### ISSUE THREAD

**Issue by madebr** [aap/librw#74]
Backtrace of running `ska2anm` without arguments is:
```
#0  0x000000000042c83d in rw::gl3::openGLFW (openparams=0x0)
    at /home/maarten/programming/librw/src/gl/gl3device.cpp:1645
#1  0x000000000042d3d7 in rw::gl3::deviceSystemGLFW (req=rw::DEVICEOPEN, arg=0x0, n=0)
    at /home/maarten/programming/librw/src/gl/gl3device.cpp:1984
#2  0x000000000040b68c in rw::Engine::open (p=0x0) at /home/maarten/programming/librw/src/engine.cpp:270
#3  0x0000000000404d4d in main (argc=1, argv=0x7fffffffdd98)
    at /home/maarten/programming/librw/tools/ska2anm/ska2anm.cpp:26
```

**Comment by aap** [comment]
right we should disable anything but the null build
